[server]
	User = "ubuntu"
	Port = "22"
	Host = "192.168.23.61"
	Pass = "1234"


[flags]
	Destr = false
	Combo = false 
	Hideme = true
	BrFile = "/home/ubuntu/test.csv"
    ConnectedUser = "ubuntu"
	Threads = 3
	Knock =[1000,2000,3000] 