[client]
	User = "wine"
	Port = "22"
	Host = "192.168.23.89"
	Pass = "1234"


[flags]
	Destr = false
	Combo = false 
	Hideme = true
	BrFile = "/home/ubuntu/test.csv"
    ConnectedUser = "ubuntu"
	Threads = 3
	KnockAlive = 6666
	KnockData = [8666,7666]