[server]
	User = "wine"
	Port = "22"
	Host = "192.168.23.89"
	Pass = "1234"


[flags]
	PreFile = "skata.txt"
	MainFile = "output_skata"
	Destr = false
	Combo = false 
	BrFile = "/home/wine/test.csv"
	Threads = 3