[server]
	User = "wine"
	Port = "22"
	Host = "192.168.23.89"
	Pass = "1234"


[flags]
	PreFile = "/tmp/prefile.txt"
	MainFile = "/tmp/mainFile"
	Destr = true
	Combo = false 
	BrFile = "/tmp/test.csv"
	Threads = 3
	Key = "mysecretkey12345"
	RundomTimeSec = 10